version: '3.8'

services:
  # Backend service (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}    
    container_name: partstock-backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app
      - ${DATA_PATH}/data:/app/data
      - ${DATA_PATH}/photos:/app/photos
    env_file:
      - .env
    restart: unless-stopped
   
  nginx:
    image: nginx:alpine
    container_name: partstock-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/static:/static  # static files from your FastAPI app
    depends_on:
      - backend
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

