version: '3.8'

services:
  # Backend service (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}    
    container_name: partstock-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ${DATA_PATH}/data:/app/data
      - ${DATA_PATH}/photos:/app/photos
    env_file:
      - .env
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

